{"cells":[{"cell_type":"markdown","metadata":{"id":"qBCv18rQTDJY"},"source":["# Laboratorio: Programaci√≥n en Python\n","\n","En este laboratorio, pondremos en pr√°ctica algunos de los conceptos que hemos aprendido recientemente. El objetivo es que implementes cada funci√≥n utilizando tres enfoques diferentes en Python: **programaci√≥n imperativa**, **programaci√≥n orientada a objetos** y **programaci√≥n funcional**.\n","\n","> **NOTA:** En este laboratorio deber√≠as intentar escribir todas las funciones por ti mismo utilizando √∫nicamente la sintaxis m√°s b√°sica de Python, sin utilizar funciones predefinidas como `len`, `count`, `sum`, `max`, `min`, `in`, etc. ¬°Dale una oportunidad! üßëüèª‚Äçüíªüë©üèª‚Äçüíª\n","\n","La celda despu√©s de cada ejercicio contiene pruebas para verificar si tu funci√≥n funciona como se espera.\n"]},{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":331},"executionInfo":{"elapsed":284,"status":"error","timestamp":1729099492090,"user":{"displayName":"CARMEN IFP IFP","userId":"01750690223671469992"},"user_tz":-120},"id":"GElpcameTDJZ","outputId":"457f6442-4889-4980-f286-fd760e756d84"},"outputs":[],"source":["from mod.testing import *\n","import unittest"]},{"cell_type":"markdown","metadata":{"id":"6ZP2-O-QTDJa"},"source":["## 1. Escribe una funci√≥n que devuelva el mayor de dos n√∫meros"]},{"cell_type":"code","execution_count":15,"metadata":{"id":"2Yc_oCFcTDJa"},"outputs":[],"source":["#tu codigo aqu√≠\n","def greater_imperativa(a, b):\n","    if a > b:\n","        return a\n","    else:\n","        return b"]},{"cell_type":"code","execution_count":16,"metadata":{"id":"TBYsYpdDTDJa","outputId":"a1f684e9-2620-49a5-c5f6-ef0d9870ccdc"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.042s\n","\n","OK\n"]}],"source":["# Para testear tu funci√≥n\n","test_greater(greater_imperativa)"]},{"cell_type":"code","execution_count":7,"metadata":{"id":"43ciFzIXTDJa"},"outputs":[],"source":["class Comparador:\n","    @staticmethod\n","    def greater_poo(a, b):\n","        return a if a > b else b\n","\n","greater_poo = Comparador.greater_poo"]},{"cell_type":"code","execution_count":17,"metadata":{"id":"BTXY4ayoTDJa","outputId":"d6f01dbb-6248-449e-87e4-97fba763af1f"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.033s\n","\n","OK\n"]}],"source":["test_greater(greater_poo)"]},{"cell_type":"code","execution_count":2,"metadata":{"id":"mHzyhl5WTDJb"},"outputs":[],"source":["greater_funcional = (lambda a, b: a if a > b else b)"]},{"cell_type":"code","execution_count":19,"metadata":{"id":"-MkiBnbJTDJb","outputId":"4e76bc10-6547-468f-c214-8062d8301b93"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.043s\n","\n","OK\n"]}],"source":["test_greater(greater_funcional)"]},{"cell_type":"markdown","metadata":{"id":"Xo_OeYnYTDJb"},"source":["## 2. Ahora escribe una funci√≥n que devuelva el elemento m√°s grande de una lista numerica"]},{"cell_type":"code","execution_count":3,"metadata":{"id":"K3w0ScvcTDJb"},"outputs":[],"source":["#tu codigo aqu√≠\n","def greatest_imperativa(arr):\n","    if not arr:  # Manejar el caso de una lista vac√≠a\n","        return None\n","\n","    max_num = arr[0]  # Asumimos que el primer elemento es el m√°ximo\n","    index = 1\n","\n","    while True:\n","        try:\n","            if arr[index] > max_num:  # Comparamos el elemento actual con max_num\n","                max_num = arr[index]  # Actualizamos max_num si encontramos un nuevo m√°ximo\n","            index += 1  # Aumentamos el √≠ndice para continuar al siguiente elemento\n","        except IndexError:\n","            break  # Si index excede el rango, salimos del bucle\n","\n","    return max_num\n"]},{"cell_type":"code","execution_count":4,"metadata":{"id":"hxYNFp9FTDJb","outputId":"0a4f0079-5f1b-4770-c697-b551645ba97b"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.049s\n","\n","OK\n"]}],"source":["# Para testear tu funci√≥n\n","test_greatest(greatest_imperativa)"]},{"cell_type":"code","execution_count":5,"metadata":{"executionInfo":{"elapsed":304,"status":"ok","timestamp":1729099076428,"user":{"displayName":"CARMEN IFP IFP","userId":"01750690223671469992"},"user_tz":-120},"id":"WsrWpE-iTDJb"},"outputs":[],"source":["class test_greatest:\n","  def __init__(self, arr):\n","    self.arr = arr\n","\n","  def generar(arr):\n","    max_num = arr[0]  # Asumimos que el primer elemento es el m√°ximo\n","    index = 1\n","    while True:\n","        try:\n","            if arr[index] > max_num:  # Comparamos el elemento actual con max_num\n","                max_num = arr[index]  # Actualizamos max_num si encontramos un nuevo m√°ximo\n","            index += 1  # Aumentamos el √≠ndice para continuar al siguiente elemento\n","        except IndexError:\n","            break  # Si index excede el rango, salimos del bucle\n","\n","    return max_num"]},{"cell_type":"code","execution_count":6,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"elapsed":262,"status":"error","timestamp":1729099080322,"user":{"displayName":"CARMEN IFP IFP","userId":"01750690223671469992"},"user_tz":-120},"id":"qpzeApTiTDJc","outputId":"bac10b58-62f2-4a7b-ab16-ff651949eb25"},"outputs":[{"data":{"text/plain":["<__main__.test_greatest at 0x21b51e93920>"]},"execution_count":6,"metadata":{},"output_type":"execute_result"}],"source":["test_greatest(test_greatest)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_x3lyv_STDJc"},"outputs":[],"source":["greater_funcional= lambda arr : 1 if max_num =)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"jQxO-U4wTDJc"},"outputs":[],"source":["test_greatest(greatest_funcional)"]},{"cell_type":"markdown","metadata":{"id":"xGndo1EjTDJc"},"source":["## 3. Escribe una funci√≥n que sume todos los elementos de una lista"]},{"cell_type":"code","execution_count":11,"metadata":{"id":"qoktJZhqTDJc"},"outputs":[],"source":["#tu codigo aqu√≠\n","def sum_imperativa (arr):\n","    sumatori=0\n","    index=0\n","    while True:\n","        try:\n","            sumatori += arr[index] \n","            index += 1\n","        except IndexError:\n","            break \n","    return sumatori"]},{"cell_type":"code","execution_count":12,"metadata":{"id":"xpiCC2YfTDJc"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.045s\n","\n","OK\n"]}],"source":["# Para testear tu funci√≥n\n","test_sum(sum_imperativa)"]},{"cell_type":"code","execution_count":30,"metadata":{"id":"H9aXzhq1TDJc"},"outputs":[],"source":["class sum_poo:\n","    def __init__(self, arr):\n","        self.arr = arr\n","    def sum(self,arr):\n","        sumatori=0\n","        index=0\n","        while True:\n","            try:\n","                sumatori += arr[index] \n","                index += 1\n","            except IndexError:\n","                break \n","        return sumatori"]},{"cell_type":"code","execution_count":31,"metadata":{"id":"zK-wh4D8TDJc"},"outputs":[{"name":"stderr","output_type":"stream","text":["FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != 1062 : Should be 1062\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != -5492 : Should be -5492\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91910> != -1311 : Should be -1311\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != -5096 : Should be -5096\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92450> != 4105 : Should be 4105\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != 5001 : Should be 5001\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B520A5880> != 613 : Should be 613\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != 495 : Should be 495\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B520A6E10> != 2324 : Should be 2324\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8890> != 1910 : Should be 1910\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B520A63F0> != 8151 : Should be 8151\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B520A6B40> != -6177 : Should be -6177\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEB110> != 4288 : Should be 4288\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA840> != 4799 : Should be 4799\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA5D0> != -822 : Should be -822\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA420> != 4006 : Should be 4006\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA330> != -779 : Should be -779\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA900> != 1207 : Should be 1207\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA5D0> != -10387 : Should be -10387\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA030> != 1903 : Should be 1903\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E93D70> != 8615 : Should be 8615\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92780> != 2984 : Should be 2984\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEABD0> != 1008 : Should be 1008\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E93D70> != 5217 : Should be 5217\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92450> != 6463 : Should be 6463\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E919D0> != -1085 : Should be -1085\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E93BF0> != -7574 : Should be -7574\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E913D0> != -3863 : Should be -3863\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E90CB0> != -1732 : Should be -1732\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E90E90> != 5425 : Should be 5425\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEABD0> != 7217 : Should be 7217\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1D520> != -10221 : Should be -10221\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1E600> != -5718 : Should be -5718\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C350> != 7894 : Should be 7894\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C680> != 5502 : Should be 5502\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C740> != 7206 : Should be 7206\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C320> != 1518 : Should be 1518\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F680> != -2643 : Should be -2643\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F770> != 4834 : Should be 4834\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F0E0> != 1707 : Should be 1707\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1D940> != -1094 : Should be -1094\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F3B0> != -5479 : Should be -5479\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1CA70> != 35 : Should be 35\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F050> != -6914 : Should be -6914\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FBF0> != -2369 : Should be -2369\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E913D0> != 4220 : Should be 4220\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E913D0> != 50 : Should be 50\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91250> != -6791 : Should be -6791\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE8740> != 989 : Should be 989\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E913D0> != 104 : Should be 104\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA690> != -1291 : Should be -1291\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92840> != 6777 : Should be 6777\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E90740> != 1273 : Should be 1273\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E912E0> != -2380 : Should be -2380\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA5D0> != -1242 : Should be -1242\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92EA0> != 5696 : Should be 5696\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA5A0> != 3375 : Should be 3375\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEB170> != -190 : Should be -190\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEAEA0> != -17 : Should be -17\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FE9B80> != 1895 : Should be 1895\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEB170> != -619 : Should be -619\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F050> != 11886 : Should be 11886\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91B80> != 2688 : Should be 2688\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1DA30> != -671 : Should be -671\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FBF0> != -2840 : Should be -2840\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1EC90> != -2958 : Should be -2958\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1ED50> != 1354 : Should be 1354\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1F770> != 4445 : Should be 4445\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FEF0> != 5893 : Should be 5893\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C140> != 4052 : Should be 4052\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1E930> != -3325 : Should be -3325\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1DE50> != 3371 : Should be 3371\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1D040> != 2675 : Should be 2675\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1D5E0> != -4981 : Should be -4981\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C8F0> != -819 : Should be -819\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C8F0> != -220 : Should be -220\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51DE2330> != -2449 : Should be -2449\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51DE0FE0> != 583 : Should be 583\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1DA60> != 9754 : Should be 9754\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1CDD0> != -998 : Should be -998\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FB90> != 1580 : Should be 1580\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C320> != -1386 : Should be -1386\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FBF0> != 10103 : Should be 10103\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1FC20> != 11594 : Should be 11594\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1C320> != 6735 : Should be 6735\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1E600> != 2500 : Should be 2500\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51FEA3F0> != -221 : Should be -221\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51F1DD00> != -2767 : Should be -2767\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91B80> != -1532 : Should be -1532\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E93170> != -650 : Should be -650\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E93170> != 2900 : Should be 2900\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92240> != 438 : Should be 438\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E90740> != -6125 : Should be -6125\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E919D0> != -309 : Should be -309\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91C40> != 2839 : Should be 2839\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92450> != -2307 : Should be -2307\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E919D0> != -467 : Should be -467\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E91250> != 6432 : Should be 6432\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E921B0> != 4260 : Should be 4260\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_sum.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 53, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: <__main__.sum_poo object at 0x0000021B51E92BD0> != 818 : Should be 818\n","\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.064s\n","\n","FAILED (failures=100)\n"]}],"source":["test_sum(sum_poo)\n"]},{"cell_type":"code","execution_count":34,"metadata":{"id":"ukRCQuqHTDJc"},"outputs":[],"source":["sum_funcional = lambda arr: 0 if arr==[] else reduce (lambda a,b: a+b,arr)"]},{"cell_type":"code","execution_count":35,"metadata":{"id":"5YNm7T1GTDJc"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.050s\n","\n","OK\n"]}],"source":["test_sum(sum_funcional)"]},{"cell_type":"markdown","metadata":{"id":"eyy6ZUjlTDJc"},"source":["## 4. Escribe otra funci√≥n que multiplique todos los elementos de una lista"]},{"cell_type":"code","execution_count":26,"metadata":{"id":"Yb_VR_WmTDJc"},"outputs":[],"source":["#tu codigo aqu√≠\n","def mult_imperativa (arr):\n","    multiplicador=1\n","    index=0\n","    while True:\n","        try:\n","            multiplicador *= arr[index] \n","            index += 1\n","        except IndexError:\n","            break \n","    return multiplicador\n"]},{"cell_type":"code","execution_count":27,"metadata":{"id":"E4pHhbIpTDJd"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.045s\n","\n","OK\n"]}],"source":["# Para testear tu funci√≥n\n","test_mult(mult_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"joCADQQFTDJd"},"outputs":[],"source":["class mult_poo:\n","    "]},{"cell_type":"code","execution_count":null,"metadata":{"id":"BVt2z6TETDJd"},"outputs":[],"source":["test_mult(mult_poo)\n"]},{"cell_type":"markdown","metadata":{},"source":[]},{"cell_type":"code","execution_count":38,"metadata":{"id":"HJON4JcvTDJd"},"outputs":[],"source":["mult_funcional = lambda arr:reduce (lambda a,b: a*b,arr,1) if arr != [] else 0"]},{"cell_type":"code","execution_count":37,"metadata":{"id":"xORzzjCkTDJd"},"outputs":[{"name":"stderr","output_type":"stream","text":["....................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.047s\n","\n","OK\n"]}],"source":["test_mult(mult_funcional)\n"]},{"cell_type":"markdown","metadata":{"id":"79ywWPJmTDJd"},"source":["## 5. Ahora combina esas dos ideas y escribe una funci√≥n que reciba una lista y ya sea \"+\" o \"*\", y produzca el resultado acorde"]},{"cell_type":"code","execution_count":39,"metadata":{"id":"-XYMjDORTDJd"},"outputs":[],"source":["#tu codigo aqu√≠\n","def operaciones_imperativa(arr,signo):\n","    if signo == \"+\":\n","        return sum_imperativa(arr)\n","    elif signo == \"*\":\n","        return mult_imperativa(arr)\n","\n"]},{"cell_type":"code","execution_count":40,"metadata":{"id":"JrvQpo9CTDJd"},"outputs":[{"name":"stderr","output_type":"stream","text":["FF.F.F.FFFFF...F..FFF...F....F.F.....F.F....F.FFFFF.....FF..FFFFF.F..FF.F....FFF.F..FF.F.F.FF..FFFF.\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 66 : Should be 66\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10 : Should be 10\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 51 : Should be 51\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: -604661760000000 != -4 : Should be -4\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 53 : Should be 53\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -25 : Should be -25\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 22649241600 != 29 : Should be 29\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 72 : Should be 72\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 839965883904000000 != -5 : Should be -5\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -7 : Should be -7\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -32 : Should be -32\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -15 : Should be -15\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 37 : Should be 37\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -101 : Should be -101\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 34 : Should be 34\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 9 : Should be 9\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 25 : Should be 25\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 17 : Should be 17\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -48 : Should be -48\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -69 : Should be -69\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 21742388846056282521600000 != -6 : Should be -6\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 15 : Should be 15\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 23 : Should be 23\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -9 : Should be -9\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 16 : Should be 16\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -7 : Should be -7\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -5 : Should be -5\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -68 : Should be -68\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10 : Should be 10\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: -3715891200000000 != 29 : Should be 29\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 42 : Should be 42\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -51 : Should be -51\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -7 : Should be -7\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 29 : Should be 29\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 68 : Should be 68\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -13 : Should be -13\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -4 : Should be -4\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: -1012118780425435906855403520000000000000000 != -4 : Should be -4\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -50 : Should be -50\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -19 : Should be -19\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 10536960000000 != 27 : Should be 27\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -91 : Should be -91\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: -5832000 != -12 : Should be -12\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 35 : Should be 35\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -40 : Should be -40\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 31 : Should be 31\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -22 : Should be -22\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != -95 : Should be -95\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 91, in runTest\n","    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: -6221969510400000000 != 35 : Should be 35\n","\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.056s\n","\n","FAILED (failures=49)\n"]}],"source":["# Para testear tu funci√≥n\n","test_operations(operaciones_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"1rV2A28xTDJd"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"6Z5FmEayTDJd"},"outputs":[],"source":["test_operations(operaciones_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TPtcJFU-TDJd"},"outputs":[],"source":["operaciones_funcional = lambda arr,signo: lambda( if signo ==\"+\" ,sum_poo(arr))"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"U8My7kk-TDJe"},"outputs":[],"source":["test_operations(operaciones_funcional)"]},{"cell_type":"markdown","metadata":{"id":"Swk9Jb0ATDJe"},"source":["## 6. Escribe una funci√≥n que devuelva el factorial de un n√∫mero."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ZH3t53n4TDJe"},"outputs":[],"source":["# F√≥rmula factorial\n","# n! = n * (n - 1) *...*1\n","\n","# Este c√≥digo define una funci√≥n llamada \"factorial\" que toma una entrada \"n\". La funci√≥n utiliza un bucle for para iterar a trav√©s del rango de n√∫meros\n","# desde 1 hasta n+1. Para cada n√∫mero en ese rango, multiplica el valor actual de x por el n√∫mero en el rango. Al final del bucle,\n","# la funci√≥n devuelve el valor final de x, que ser√° el factorial del n√∫mero de entrada \"n\".\n","\n","# El factorial de un entero positivo n es el producto de todos los enteros positivos menores o iguales a n.\n","# Por ejemplo, el factorial de 6 (escrito \"6!\") es 6 * 5 * 4 * 3 * 2 * 1 = 720.\n","\n","# As√≠ que esta funci√≥n toma una entrada de cualquier entero positivo y devuelve el factorial de ese n√∫mero."]},{"cell_type":"code","execution_count":49,"metadata":{"id":"-rrFBAUgTDJh"},"outputs":[],"source":["#tu codigo aqu√≠\n","def factorial_imperativa(n):\n","    factorial=0\n","    if n <= 0:\n","        return None\n","\n","    while n>0:\n","        try:\n","            factorial*=n\n","            n=n-1\n","        except Exception:\n","            break \n","    return factorial\n"]},{"cell_type":"code","execution_count":50,"metadata":{"id":"bgOemqzNTDJi"},"outputs":[{"name":"stderr","output_type":"stream","text":["FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 8841761993739701954543616000000 : Should be 8841761993739701954543616000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1551118753287382280224243016469303211063259720016986112000000000000 : Should be 1551118753287382280224243016469303211063259720016986112000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 8222838654177922817725562880000000 : Should be 8222838654177922817725562880000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1405006117752879898543142606244511569936384000000000 : Should be 1405006117752879898543142606244511569936384000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 8841761993739701954543616000000 : Should be 8841761993739701954543616000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 36471110918188685288249859096605464427167[49 chars]00000 : Should be 36471110918188685288249859096605464427167635314049524593701628500267962436943872000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 13868311854568983573793901972038940634590[35 chars]00000 : Should be 138683118545689835737939019720389406345902876772687432540821294940160000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 93326215443944152681699238856266700490715[112 chars]00000 : Should be 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2432902008176640000 : Should be 2432902008176640000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1 : Should be 1\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2350561331282878571829474910515074683828862318181142924420699914240000000000000 : Should be 2350561331282878571829474910515074683828862318181142924420699914240000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11978571669969891796072783721689098736458[55 chars]00000 : Should be 11978571669969891796072783721689098736458938142546425857555362864628009582789845319680000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 3628800 : Should be 3628800\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 61234458376886086861524070385274672740778[58 chars]00000 : Should be 61234458376886086861524070385274672740778091784697328983823014963978384987221689274204160000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 51090942171709440000 : Should be 51090942171709440000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 44701154615126843408912571381250511100768[60 chars]00000 : Should be 4470115461512684340891257138125051110076800700282905015819080092370422104067183317016903680000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 710998587804863451854045647463724949736497978881168458687447040000000000000 : Should be 710998587804863451854045647463724949736497978881168458687447040000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 18548264225739843911479684564554628438022[89 chars]00000 : Should be 185482642257398439114796845645546284380220968949399346684421580986889562184028199319100141244804501828416633516851200000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 14518309202828586963407078408630828498374[68 chars]00000 : Should be 145183092028285869634070784086308284983740379224208358846781574688061991349156420080065207861248000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 815915283247897734345611269596115894272000000000 : Should be 815915283247897734345611269596115894272000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10333147966386144929666651337523200000000 : Should be 10333147966386144929666651337523200000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 710998587804863451854045647463724949736497978881168458687447040000000000000 : Should be 710998587804863451854045647463724949736497978881168458687447040000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 479001600 : Should be 479001600\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 50758021387722479880085681217662522722600[38 chars]00000 : Should be 507580213877224798800856812176625227226004528988036003099405939480985600000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 17112245242814131137246833888127283909227[53 chars]00000 : Should be 171122452428141311372468338881272839092270544893520369393648040923257279754140647424000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 61234458376886086861524070385274672740778[58 chars]00000 : Should be 61234458376886086861524070385274672740778091784697328983823014963978384987221689274204160000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12413915592536072670862289047373375038521486354677760000000000 : Should be 12413915592536072670862289047373375038521486354677760000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 99167793487094968920957140154189380115818[104 chars]00000 : Should be 991677934870949689209571401541893801158183648651267795444376054838492222809091499987689476037000748982075094738965754305639874560000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 28171041143805502769494794422606115948005[83 chars]00000 : Should be 281710411438055027694947944226061159480056634330574206405101912752560026159795933451040286452340924018275123200000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2 : Should be 2\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 295232799039604140847618609643520000000 : Should be 295232799039604140847618609643520000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 620448401733239439360000 : Should be 620448401733239439360000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 13520015276784029625516656875949514214758[95 chars]00000 : Should be 135200152767840296255166568759495142147586866476906677791741734597153670771559994765685283954750449427751168336768008192000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2350561331282878571829474910515074683828862318181142924420699914240000000000000 : Should be 2350561331282878571829474910515074683828862318181142924420699914240000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 80658175170943878571660636856403766975289505440883277824000000000000 : Should be 80658175170943878571660636856403766975289505440883277824000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11567725070816415747592051623062404362147[99 chars]00000 : Should be 1156772507081641574759205162306240436214753229576413535186142281213246807121467315215203289516844845303838996289387078090752000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 20922789888000 : Should be 20922789888000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 71569457046263802294811533723186532165584[73 chars]00000 : Should be 71569457046263802294811533723186532165584657342365752577109445058227039255480148842668944867280814080000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 93326215443944152681699238856266700490715[112 chars]00000 : Should be 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1405006117752879898543142606244511569936384000000000 : Should be 1405006117752879898543142606244511569936384000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 57971260207473679858797342315781091054123[75 chars]00000 : Should be 5797126020747367985879734231578109105412357244731625958745865049716390179693892056256184534249745940480000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2350561331282878571829474910515074683828862318181142924420699914240000000000000 : Should be 2350561331282878571829474910515074683828862318181142924420699914240000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11567725070816415747592051623062404362147[99 chars]00000 : Should be 1156772507081641574759205162306240436214753229576413535186142281213246807121467315215203289516844845303838996289387078090752000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 371993326789901217467999448150835200000000 : Should be 371993326789901217467999448150835200000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 815915283247897734345611269596115894272000000000 : Should be 815915283247897734345611269596115894272000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 87178291200 : Should be 87178291200\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1124000727777607680000 : Should be 1124000727777607680000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12413915592536072670862289047373375038521486354677760000000000 : Should be 12413915592536072670862289047373375038521486354677760000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 13520015276784029625516656875949514214758[95 chars]00000 : Should be 135200152767840296255166568759495142147586866476906677791741734597153670771559994765685283954750449427751168336768008192000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 8841761993739701954543616000000 : Should be 8841761993739701954543616000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11567725070816415747592051623062404362147[99 chars]00000 : Should be 1156772507081641574759205162306240436214753229576413535186142281213246807121467315215203289516844845303838996289387078090752000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12413915592536072670862289047373375038521486354677760000000000 : Should be 12413915592536072670862289047373375038521486354677760000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 36471110918188685288249859096605464427167[49 chars]00000 : Should be 36471110918188685288249859096605464427167635314049524593701628500267962436943872000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10329978488239059262599702099394727095397[103 chars]00000 : Should be 10329978488239059262599702099394727095397746340117372869212250571234293987594703124871765375385424468563282236864226607350415360000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2350561331282878571829474910515074683828862318181142924420699914240000000000000 : Should be 2350561331282878571829474910515074683828862318181142924420699914240000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11324281178206297831457521158732046228731[70 chars]00000 : Should be 11324281178206297831457521158732046228731749579488251990048962825668835325234200766245086213177344000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2432902008176640000 : Should be 2432902008176640000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 18548264225739843911479684564554628438022[89 chars]00000 : Should be 185482642257398439114796845645546284380220968949399346684421580986889562184028199319100141244804501828416633516851200000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 120 : Should be 120\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 17112245242814131137246833888127283909227[53 chars]00000 : Should be 171122452428141311372468338881272839092270544893520369393648040923257279754140647424000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 17112245242814131137246833888127283909227[53 chars]00000 : Should be 171122452428141311372468338881272839092270544893520369393648040923257279754140647424000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2658271574788448768043625811014615890319638528000000000 : Should be 2658271574788448768043625811014615890319638528000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 2 : Should be 2\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 14518309202828586963407078408630828498374[68 chars]00000 : Should be 145183092028285869634070784086308284983740379224208358846781574688061991349156420080065207861248000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 21077572983795277172136005186993895952297[87 chars]00000 : Should be 2107757298379527717213600518699389595229783738061356212322972511214654115727593174080683423236414793504734471782400000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10888869450418352160768000000 : Should be 10888869450418352160768000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 6227020800 : Should be 6227020800\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 13868311854568983573793901972038940634590[35 chars]00000 : Should be 138683118545689835737939019720389406345902876772687432540821294940160000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10329978488239059262599702099394727095397[103 chars]00000 : Should be 10329978488239059262599702099394727095397746340117372869212250571234293987594703124871765375385424468563282236864226607350415360000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 39916800 : Should be 39916800\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 403291461126605635584000000 : Should be 403291461126605635584000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 10333147966386144929666651337523200000000 : Should be 10333147966386144929666651337523200000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 54434493907744306400372924024784275264429[47 chars]00000 : Should be 544344939077443064003729240247842752644293064388798874532860126869671081148416000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 44701154615126843408912571381250511100768[60 chars]00000 : Should be 4470115461512684340891257138125051110076800700282905015819080092370422104067183317016903680000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1551118753287382280224243016469303211063259720016986112000000000000 : Should be 1551118753287382280224243016469303211063259720016986112000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 18548264225739843911479684564554628438022[89 chars]00000 : Should be 185482642257398439114796845645546284380220968949399346684421580986889562184028199319100141244804501828416633516851200000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 265252859812191058636308480000000 : Should be 265252859812191058636308480000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 295232799039604140847618609643520000000 : Should be 295232799039604140847618609643520000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 28171041143805502769494794422606115948005[83 chars]00000 : Should be 281710411438055027694947944226061159480056634330574206405101912752560026159795933451040286452340924018275123200000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 4274883284060025564298013753389399649690343788366813724672000000000000 : Should be 4274883284060025564298013753389399649690343788366813724672000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 31469973260387937525653122354950764088012[40 chars]00000 : Should be 31469973260387937525653122354950764088012280797258232192163168247821107200000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12688693218588416410343338933516148080286[44 chars]00000 : Should be 126886932185884164103433389335161480802865516174545192198801894375214704230400000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1 : Should be 1\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 83209871127413901442763411832233643807541[36 chars]00000 : Should be 8320987112741390144276341183223364380754172606361245952449277696409600000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 16507955160908461081216919262453619309839[91 chars]00000 : Should be 16507955160908461081216919262453619309839666236496541854913520707833171034378509739399912570787600662729080382999756800000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 371993326789901217467999448150835200000000 : Should be 371993326789901217467999448150835200000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 19826083154044400641161467083618981375447[42 chars]00000 : Should be 1982608315404440064116146708361898137544773690227268628106279599612729753600000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 71569457046263802294811533723186532165584[73 chars]00000 : Should be 71569457046263802294811533723186532165584657342365752577109445058227039255480148842668944867280814080000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 119622220865480194561963161495657715064383733760000000000 : Should be 119622220865480194561963161495657715064383733760000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 11324281178206297831457521158732046228731[70 chars]00000 : Should be 11324281178206297831457521158732046228731749579488251990048962825668835325234200766245086213177344000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 99167793487094968920957140154189380115818[104 chars]00000 : Should be 991677934870949689209571401541893801158183648651267795444376054838492222809091499987689476037000748982075094738965754305639874560000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 371993326789901217467999448150835200000000 : Should be 371993326789901217467999448150835200000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 1124000727777607680000 : Should be 1124000727777607680000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 304888344611713860501504000000 : Should be 304888344611713860501504000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12688693218588416410343338933516148080286[44 chars]00000 : Should be 126886932185884164103433389335161480802865516174545192198801894375214704230400000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 13520015276784029625516656875949514214758[95 chars]00000 : Should be 135200152767840296255166568759495142147586866476906677791741734597153670771559994765685283954750449427751168336768008192000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 12438414054641307255475324325873553077577[97 chars]00000 : Should be 12438414054641307255475324325873553077577991715875414356840239582938137710983519518443046123837041347353107486982656753664000000000000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 230843697339241380472092742683027581083278564571807941132288000000000000 : Should be 230843697339241380472092742683027581083278564571807941132288000000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 815915283247897734345611269596115894272000000000 : Should be 815915283247897734345611269596115894272000000000\n","\n","======================================================================\n","FAIL: runTest (mod.testing.test_factorial.<locals>.TestKnown.runTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"e:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py\", line 118, in runTest\n","    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n","AssertionError: 0 != 18548264225739843911479684564554628438022[89 chars]00000 : Should be 185482642257398439114796845645546284380220968949399346684421580986889562184028199319100141244804501828416633516851200000000000000000000\n","\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.066s\n","\n","FAILED (failures=100)\n"]}],"source":["# Para testear tu funci√≥n\n","test_factorial(factorial_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"cTgIzYVxTDJi"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Vjh5HCBITDJi"},"outputs":[],"source":["test_factorial(factorial_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"LbmvwKp6TDJi"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"GdEerWEuTDJi"},"outputs":[],"source":["test_factorial(factorial_funcional)"]},{"cell_type":"markdown","metadata":{"id":"0I6y4bd3TDJi"},"source":["## 7. Escribe una funci√≥n que tome una lista y devuelva una lista de los valores √∫nicos.\n","\n","`NOTE: No podemos usar set. ü§î`"]},{"cell_type":"code","execution_count":61,"metadata":{"id":"qLFSVtzRTDJi"},"outputs":[],"source":["#tu codigo aqu√≠\n","def unique_imperativa (arr):\n","    unique_list=[]\n","    index=0\n","\n","    while True:\n","        try:\n","            item =arr[index]\n","            is_unique = True\n","            index +=1\n","        except IndexError:\n","            break"]},{"cell_type":"code","execution_count":62,"metadata":{"id":"Mkete-wKTDJj"},"outputs":[{"ename":"KeyboardInterrupt","evalue":"","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)","Cell \u001b[1;32mIn[62], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# Para testear tu funci√≥n\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[43mtest_unique\u001b[49m\u001b[43m(\u001b[49m\u001b[43munique_imperativa\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32me:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py:143\u001b[0m, in \u001b[0;36mtest_unique\u001b[1;34m(fn)\u001b[0m\n\u001b[0;32m    141\u001b[0m         arr\u001b[38;5;241m.\u001b[39mappend(random\u001b[38;5;241m.\u001b[39mrandint(\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m100\u001b[39m, \u001b[38;5;241m100\u001b[39m))\n\u001b[0;32m    142\u001b[0m     suite\u001b[38;5;241m.\u001b[39maddTest(TestKnown(arr, \u001b[38;5;28mset\u001b[39m(arr)))\n\u001b[1;32m--> 143\u001b[0m \u001b[43munittest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mTextTestRunner\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43msuite\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\runner.py:240\u001b[0m, in \u001b[0;36mTextTestRunner.run\u001b[1;34m(self, test)\u001b[0m\n\u001b[0;32m    238\u001b[0m     startTestRun()\n\u001b[0;32m    239\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 240\u001b[0m     \u001b[43mtest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    241\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    242\u001b[0m     stopTestRun \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(result, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mstopTestRun\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\suite.py:84\u001b[0m, in \u001b[0;36mBaseTestSuite.__call__\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__call__\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwds):\n\u001b[1;32m---> 84\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\suite.py:122\u001b[0m, in \u001b[0;36mTestSuite.run\u001b[1;34m(self, result, debug)\u001b[0m\n\u001b[0;32m    119\u001b[0m         \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[0;32m    121\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m debug:\n\u001b[1;32m--> 122\u001b[0m     \u001b[43mtest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    123\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    124\u001b[0m     test\u001b[38;5;241m.\u001b[39mdebug()\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:690\u001b[0m, in \u001b[0;36mTestCase.__call__\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m    689\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__call__\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwds):\n\u001b[1;32m--> 690\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:634\u001b[0m, in \u001b[0;36mTestCase.run\u001b[1;34m(self, result)\u001b[0m\n\u001b[0;32m    632\u001b[0m outcome\u001b[38;5;241m.\u001b[39mexpecting_failure \u001b[38;5;241m=\u001b[39m expecting_failure\n\u001b[0;32m    633\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m outcome\u001b[38;5;241m.\u001b[39mtestPartExecutor(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 634\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_callTestMethod\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtestMethod\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    635\u001b[0m outcome\u001b[38;5;241m.\u001b[39mexpecting_failure \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m    636\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m outcome\u001b[38;5;241m.\u001b[39mtestPartExecutor(\u001b[38;5;28mself\u001b[39m):\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:589\u001b[0m, in \u001b[0;36mTestCase._callTestMethod\u001b[1;34m(self, method)\u001b[0m\n\u001b[0;32m    588\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_callTestMethod\u001b[39m(\u001b[38;5;28mself\u001b[39m, method):\n\u001b[1;32m--> 589\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[43mmethod\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    590\u001b[0m         warnings\u001b[38;5;241m.\u001b[39mwarn(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mIt is deprecated to return a value that is not None from a \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m    591\u001b[0m                       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtest case (\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmethod\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m)\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;167;01mDeprecationWarning\u001b[39;00m, stacklevel\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m3\u001b[39m)\n","File \u001b[1;32me:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py:135\u001b[0m, in \u001b[0;36mtest_unique.<locals>.TestKnown.runTest\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    134\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrunTest\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 135\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39massertEqual(\u001b[38;5;28mset\u001b[39m(\u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minput\u001b[49m\u001b[43m)\u001b[49m), \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moutput, \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShould be \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moutput\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n","Cell \u001b[1;32mIn[61], line 6\u001b[0m, in \u001b[0;36munique_imperativa\u001b[1;34m(arr)\u001b[0m\n\u001b[0;32m      3\u001b[0m unique_list\u001b[38;5;241m=\u001b[39m[]\n\u001b[0;32m      4\u001b[0m index\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m\n\u001b[1;32m----> 6\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[0;32m      7\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m      8\u001b[0m         item \u001b[38;5;241m=\u001b[39marr[index]\n","\u001b[1;31mKeyboardInterrupt\u001b[0m: "]}],"source":["# Para testear tu funci√≥n\n","test_unique(unique_imperativa)"]},{"cell_type":"code","execution_count":52,"metadata":{"id":"tVMeFCUdTDJj"},"outputs":[],"source":["class Unique:\n","    def unique_poo(arr):\n","        unique_list =[]\n","        index =0\n","\n","        while True:\n","            try:\n","                item =arr[index]\n","                if Unique.is_unique(item,unique_list):\n","                    unique_list.append(item)\n","                index +=1\n","                \n","            except IndexError:\n","                break\n","    def is_unique(item, unique_list):\n","        unique_index=0\n","\n","        while True:\n","            try:\n","                if unique_list[unique_index] == item:\n","                    return False\n","                unique_index +=1\n","            except IndexError:\n","                break\n","        return True"]},{"cell_type":"code","execution_count":53,"metadata":{"id":"P_X0IY9cTDJj"},"outputs":[{"ename":"NameError","evalue":"name 'unique_poo' is not defined","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[1;32mIn[53], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m test_unique(\u001b[43munique_poo\u001b[49m)\n","\u001b[1;31mNameError\u001b[0m: name 'unique_poo' is not defined"]}],"source":["test_unique(unique_poo)"]},{"cell_type":"code","execution_count":54,"metadata":{"id":"A_4JAVRRTDJj"},"outputs":[],"source":["unique_funcional = lambda arr: reduce (\n","    lambda acc,item: acc + [item] if reduce( \n","        lambda x,y :  x or (y ==item),acc,False)\n","        ==False else acc,arr,[]\n",")"]},{"cell_type":"code","execution_count":55,"metadata":{"id":"lVgu6DlXTDJj"},"outputs":[{"name":"stderr","output_type":"stream","text":["...."]},{"name":"stderr","output_type":"stream","text":["................................................................................................\n","----------------------------------------------------------------------\n","Ran 100 tests in 0.521s\n","\n","OK\n"]}],"source":["test_unique(unique_funcional)\n"]},{"cell_type":"markdown","metadata":{"id":"bpDs_Pt5TDJj"},"source":["## 8. Escribe una funci√≥n que devuelva la moda de una lista, es decir: el elemento que aparece m√°s veces.\n","\n","`NOTE: No se debe usar count... üßê`"]},{"cell_type":"code","execution_count":65,"metadata":{"id":"tJ1Av7sjTDJj"},"outputs":[],"source":["#tu codigo aqu√≠\n","def moda_imperativa (arr):\n","    unique_list = unique_imperativa(arr)\n","    max_frecuencia =-1\n","    moda = None\n","\n","    unique_index=0\n","    while True:\n","        try:\n","            num= unique_list[unique_index]\n","            frecuencia =0\n","            index =0\n","\n","            while True:\n","                try:\n","                    if arr[index]==num:\n","                        frecuencia +=1\n","                    index +=1\n","                except IndexError:\n","                    break\n","            if frecuencia > max_frecuencia:\n","                max_frecuencia = frecuencia\n","                moda = num\n","                \n","            unique_index +=1\n","\n","        except IndexError:\n","            break\n","\n","        return moda"]},{"cell_type":"code","execution_count":68,"metadata":{"id":"zTlQ54neTDJj"},"outputs":[{"ename":"KeyboardInterrupt","evalue":"","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)","Cell \u001b[1;32mIn[68], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# Para testear tu funci√≥n\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[43mtest_mode\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmoda_imperativa\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32me:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py:163\u001b[0m, in \u001b[0;36mtest_mode\u001b[1;34m(fn)\u001b[0m\n\u001b[0;32m    161\u001b[0m     arr \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m [random\u001b[38;5;241m.\u001b[39mrandint(\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m25\u001b[39m)] \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m50\u001b[39m\n\u001b[0;32m    162\u001b[0m     suite\u001b[38;5;241m.\u001b[39maddTest(TestKnown(arr, mode(arr)))\n\u001b[1;32m--> 163\u001b[0m \u001b[43munittest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mTextTestRunner\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43msuite\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\runner.py:240\u001b[0m, in \u001b[0;36mTextTestRunner.run\u001b[1;34m(self, test)\u001b[0m\n\u001b[0;32m    238\u001b[0m     startTestRun()\n\u001b[0;32m    239\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 240\u001b[0m     \u001b[43mtest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    241\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    242\u001b[0m     stopTestRun \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(result, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mstopTestRun\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\suite.py:84\u001b[0m, in \u001b[0;36mBaseTestSuite.__call__\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__call__\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwds):\n\u001b[1;32m---> 84\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\suite.py:122\u001b[0m, in \u001b[0;36mTestSuite.run\u001b[1;34m(self, result, debug)\u001b[0m\n\u001b[0;32m    119\u001b[0m         \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[0;32m    121\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m debug:\n\u001b[1;32m--> 122\u001b[0m     \u001b[43mtest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    123\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    124\u001b[0m     test\u001b[38;5;241m.\u001b[39mdebug()\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:690\u001b[0m, in \u001b[0;36mTestCase.__call__\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m    689\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__call__\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwds):\n\u001b[1;32m--> 690\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:634\u001b[0m, in \u001b[0;36mTestCase.run\u001b[1;34m(self, result)\u001b[0m\n\u001b[0;32m    632\u001b[0m outcome\u001b[38;5;241m.\u001b[39mexpecting_failure \u001b[38;5;241m=\u001b[39m expecting_failure\n\u001b[0;32m    633\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m outcome\u001b[38;5;241m.\u001b[39mtestPartExecutor(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 634\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_callTestMethod\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtestMethod\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    635\u001b[0m outcome\u001b[38;5;241m.\u001b[39mexpecting_failure \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m    636\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m outcome\u001b[38;5;241m.\u001b[39mtestPartExecutor(\u001b[38;5;28mself\u001b[39m):\n","File \u001b[1;32mc:\\Python312\\Lib\\unittest\\case.py:589\u001b[0m, in \u001b[0;36mTestCase._callTestMethod\u001b[1;34m(self, method)\u001b[0m\n\u001b[0;32m    588\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_callTestMethod\u001b[39m(\u001b[38;5;28mself\u001b[39m, method):\n\u001b[1;32m--> 589\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[43mmethod\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    590\u001b[0m         warnings\u001b[38;5;241m.\u001b[39mwarn(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mIt is deprecated to return a value that is not None from a \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m    591\u001b[0m                       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtest case (\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmethod\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m)\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;167;01mDeprecationWarning\u001b[39;00m, stacklevel\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m3\u001b[39m)\n","File \u001b[1;32me:\\IA\\EJERCICIOS IA\\lab_4\\lab_4\\mod\\testing.py:154\u001b[0m, in \u001b[0;36mtest_mode.<locals>.TestKnown.runTest\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    153\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrunTest\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 154\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39massertEqual(\u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minput\u001b[49m\u001b[43m)\u001b[49m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moutput, \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShould be \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moutput\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n","Cell \u001b[1;32mIn[65], line 3\u001b[0m, in \u001b[0;36mmoda_imperativa\u001b[1;34m(arr)\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmoda_imperativa\u001b[39m (arr):\n\u001b[1;32m----> 3\u001b[0m     unique_list \u001b[38;5;241m=\u001b[39m \u001b[43munique_imperativa\u001b[49m\u001b[43m(\u001b[49m\u001b[43marr\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      4\u001b[0m     max_frecuencia \u001b[38;5;241m=\u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m\n\u001b[0;32m      5\u001b[0m     moda \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n","Cell \u001b[1;32mIn[61], line 6\u001b[0m, in \u001b[0;36munique_imperativa\u001b[1;34m(arr)\u001b[0m\n\u001b[0;32m      3\u001b[0m unique_list\u001b[38;5;241m=\u001b[39m[]\n\u001b[0;32m      4\u001b[0m index\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m\n\u001b[1;32m----> 6\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[0;32m      7\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m      8\u001b[0m         item \u001b[38;5;241m=\u001b[39marr[index]\n","\u001b[1;31mKeyboardInterrupt\u001b[0m: "]}],"source":["# Para testear tu funci√≥n\n","test_mode(moda_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bpftcLoMTDJj"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TrbaTXQvTDJj"},"outputs":[],"source":["test_mode(mode_poo)"]},{"cell_type":"code","execution_count":41,"metadata":{"id":"JYPqBhCnTDJk"},"outputs":[],"source":["def moda_funcional (arr):\n","    unique_items =unique_funcional(arr)\n","\n","    count_occurrences = lambda item, arr:reduce(\n","        lambda count, x: count +1 if x == item else count,arr,0\n","    )\n","    frequency = reduce"]},{"cell_type":"code","execution_count":42,"metadata":{"id":"Y84CczNETDJk"},"outputs":[{"ename":"NameError","evalue":"name 'mode_funcional' is not defined","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[1;32mIn[42], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m test_mode(\u001b[43mmode_funcional\u001b[49m)\n","\u001b[1;31mNameError\u001b[0m: name 'mode_funcional' is not defined"]}],"source":["test_mode(mode_funcional)"]},{"cell_type":"markdown","metadata":{"id":"g76bqtiKTDJk"},"source":["## 9. Escribe una funci√≥n que calcule la desviaci√≥n est√°ndar de una lista.\n","`NOTE: no utilices librer√≠as ni ninguna funci√≥n ya construida. üòâ`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"dfnG78E_TDJk"},"outputs":[],"source":["#tu codigo aqu√≠"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"zYFfeGE5TDJk"},"outputs":[],"source":["# Para testear tu funci√≥n\n","test_stdev(st_dev_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"qCeoEXAFTDJk"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"5ieHcjrMTDJk"},"outputs":[],"source":["test_stdev(st_dev_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"GL0gpCVfTDJk"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fp1Mug64TDJk"},"outputs":[],"source":["test_stdev(st_dev_funcional)"]},{"cell_type":"markdown","metadata":{"id":"sZK_cMocTDJk"},"source":["## 10. Escribe una funci√≥n para verificar si una cadena es un pangrama, es decir: si contiene todas las letras del alfabeto al menos una vez. Ten en cuenta que las cadenas pueden contener caracteres que no son letras."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"BsMeZk_jTDJl"},"outputs":[],"source":["#tu codigo aqu√≠"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"byiPAZTXTDJl"},"outputs":[],"source":["# Para testear tu funci√≥n\n","test_pangram(is_pangram_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Ze80SCLrTDJl"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"jn0BcSRmTDJl"},"outputs":[],"source":["test_pangram(is_pangram_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"w1WvJp9aTDJl"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"iUIdNiKnTDJl"},"outputs":[],"source":["# Test para la funci√≥n funcional\n","test_pangram(is_pangram_funcional)"]},{"cell_type":"markdown","metadata":{"id":"0c7fO7vzTDJl"},"source":["## 11. Escribe una funci√≥n que reciba una cadena de palabras separadas por comas y devuelva una cadena de palabras separadas por comas ordenadas alfab√©ticamente.\n","\n","`NOTA: Puedes usar sorted pero no split y definitivamente no join! ü§™`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vNoRhIolTDJl"},"outputs":[],"source":["#tu codigo aqu√≠"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fzN4ppxpTDJm"},"outputs":[],"source":["# Para testear tu funci√≥n\n","test_alpha(sort_words_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"38hqrXlDTDJm"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Xu-WyXtgTDJm"},"outputs":[],"source":["test_alpha(sort_words_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"NrSRDP8dTDJm"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"m5wKauECTDJm"},"outputs":[],"source":["test_alpha(sort_words_funcional)"]},{"cell_type":"markdown","metadata":{"id":"bTGukloYTDJm"},"source":["## 12. Escribe una funci√≥n para verificar si una contrase√±a dada es fuerte (al menos 8 caracteres, al menos una min√∫scula, al menos una may√∫scula, al menos un n√∫mero y al menos un car√°cter especial). Deber√≠a devolver True si es fuerte y False si no lo es. Se permit el uso de regex"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vuLJaCT0TDJm"},"outputs":[],"source":["import re\n","def is_strong_password_imperativa(contrase√±a):\n","    patron_contrase√±a=r'(/(\\d{1,}[a-z]{1,}[A-Z]{1,}/g)'\n","\n","    (?=.*[a-z])(?=.*[A-Z]).{8,0}\n","\n","\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"WdW8qMgnTDJm"},"outputs":[],"source":["# Para testear tu funci√≥n\n","test_pass(is_strong_password_imperativa)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fysXEqsmTDJm"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"9GhaDaWOTDJn"},"outputs":[],"source":["test_pass(is_strong_password_poo)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"LGq4TbWVTDJn"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"4PoeC7ARTDJn"},"outputs":[],"source":["test_pass(is_strong_password_funcional)"]}],"metadata":{"colab":{"provenance":[],"toc_visible":true},"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.12.3"},"vscode":{"interpreter":{"hash":"aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"}}},"nbformat":4,"nbformat_minor":0}
